### ISSUE TITLE
[useCombobox] disabled items are selectable via keyboard when using React.StrictMode

### ISSUE THREAD

**Issue by Silverwolf90** [downshift-js/downshift#1009]
- `downshift` version: 5.2.0
- `node` version: v10.19.0
- `npm` (or `yarn`) version: npm 6.13..4

**What you did**:

Used `useCombobox` in a descendant component of `<React.StrictMode>`

**What happened**:

The disabled items are selectable via keyboard. Upon removal of `<StrictMode>`, disabled items are skipped when navigating with the keyboard (as expected).

**Reproduction repository**:

https://codesandbox.io/s/usecombobox-usage-b0gxy?file=/src/index.js

**Suggested solution**:

Not sure, but I believe it has to do with the double dispatch that strict mode performs. I think this means something isn't pure that should be.

**Comment by silviuaavram** [comment]
By pure you mean it can be related to https://github.com/downshift-js/downshift/issues/962 ?

**Comment by Silverwolf90** [comment]
To be honest I'm not sure, I do know when I was debugging last week, the useCombobox reducer was getting called twice for a single action (a behavior of strict mode to ensure that everything is pure). And that second execution didn't seem to correctly find the next disabled item index.

**Comment by lisatassone** [comment]
I don't think this is related to `<React.StrictMode>` as I am having the same problem and not using that. My versions:

- `downshift: 5.2.2`
- `npm: 6.13.4`
- `node: 10.18.1`

**Comment by lisatassone** [comment]
> I don't think this is purely related to `<React.StrictMode>` as I am having the same problem and not using that. My versions:
> 
> * `downshift: 5.2.2`
> * `npm: 6.13.4`
> * `node: 10.18.1`

Actually, my issue is caused by not passing through the 'disabled' attribute to the underlying component (which is a `li`) 🤦. I haven't done this up until now because the component is restricted to only allow recognised global/event html props that a `li` element can have and `disabled` isn't one of them. When using Typescript with React, Typescript will complain it's invalid if adding a disabled attribute directly to a `li` element. You can get around this by passing it 'in the spread' of props.

**Comment by silviuaavram** [comment]
Related to the `disabled` not being passed can you check the documentation @lisatassone and if appropriate suggest improvement?

@Silverwolf90 can you check 5.2.3-alpha.1 and see if it works? It should fix the React warning (about the reducer not being pure) and if it's related to your strict mode issue maybe it will help. Let me know!

**Comment by Silverwolf90** [comment]
Unfortunately, the behavior [still occurs with 5.2.3-alpha.1](https://codesandbox.io/s/usecombobox-usage-b0gxy?file=/src/index.js)

**Comment by lisatassone** [comment]
@silviuaavram I think this mostly due to my misunderstanding. I had an existing `MenuItem` component that I was using and adding downshift functionality to it. The `MenuItem` component did have a `disabled` prop that was used for styling the item but not included on the `li` element for reasons stated above. It wasn't until I looked further at the Downshift source code that I saw it was relying on this attribute being present on the element ref to calculate the correct index to navigate to.

I guess from the docs it's not entirely clear that is what is required for keyboard navigation to work correctly since you can pass in arguments such as item and index and they don't appear on the element as attributes - but obviously are used to apply something to the element or control events. If you think updating the documentation to be more explicit about this would be of value, I would be happy to help out.

**Comment by silviuaavram** [comment]
Upgrade to the latest version of React, it may be related to React.StrictMode. I was debugging locally and i did not get a repro, with the same example, so that was funny.

But then I increased the React version in the sandbox since it was way lower than what I knew it was my local one, and it works.

Just mind the fact that first opening the dropdown with ArrowDown will highlight the first disabled item since on opening we don't have the information about disabled (getItemProps is not yet called). To fix this you may need to check yourself if your first item (also last item if you open by ArrowUp) are disabled and do not highlight them.

Let me know if this makes sense, so i can close this issue.

**Comment by Silverwolf90** [comment]
@silviuaavram I've trie this with `react@16.13.1` and unfortunately I'm getting the same broken behavior

https://codesandbox.io/s/usecombobox-usage-b0gxy?file=/src/index.js
