### ISSUE TITLE
useCombobox: a11y status message doesn't seem to work properly compared with Downshift component

### ISSUE THREAD

**Issue by diondiondion** [downshift-js/downshift#1076]
- `downshift` version: 5.2.4

**What you did**:
I attempted to get VoiceOver on Safari (macOS) to read out the default a11y status message in the basic `useCombobox` example on Codesandbox (after I couldn't get them to work in my own implementation).

**What happened**:
The live region didn't appear to be updated reliably. The only status I got out of it (briefly) was "No results available", which was read out while some results were shown in the dropdown.
(To be clear, this is about the _status_ message, not the _selection_ message, which works fine.)

**Reproduction repository**:
https://lit4h.csb.app (This is an only minimally edited fork of [the default `useCombobox` example](https://codesandbox.io/s/usecombobox-usage-evufg) on Codesandbox.
I simply added a few more strings to the results array, all starting with "Test", to make it easier to get a changing number of results in the autocomplete menu by simply typing "Te", "Tes", "Test", or "Testi").

Compare this with the [default Downshift component example](https://codesandbox.io/s/simple-downshift-with-getrootprops-example-24s13) on Codesandbox, where the status message is correctly updated every time the displayed results change.

**Problem description**:
The a11y status message isn't updated/read out correctly when using `useCombobox` compared to the `<Downshift>` component.

**Suggested solution**:
I'm not familiar with the Downshift codebase yet, so haven't looked into the cause of it.

**Comment by diondiondion** [comment]
As a workaround for anyone facing the same issue, it's quite easy to build a declarative live region that reliably announces the dropdown status, like so:

```jsx
{isOpen &&
	<VisuallyHidden
		role="status"
		aria-live="polite"
		aria-relevant="additions text"
	>
		{getA11yStatusMessage({
			isOpen,
			resultCount: items.length,
		})}
	</VisuallyHidden>
}
```

Where `getA11yStatusMessage` is slightly adapted from the [default one](https://github.com/downshift-js/downshift/blob/45985a893a6b12e12627c2c4ba87966e8826cd65/src/utils.js#L144):
```js
function getA11yStatusMessage({isOpen, resultCount}) {
  if (!isOpen) {
    return ''
  }

  if (!resultCount) {
    return 'No results are available.'
  }

  if (resultCount > 0) {
    return `${resultCount} result${
      resultCount === 1 ? ' is' : 's are'
    } available, use up and down arrow keys to navigate. Press Enter key to select.`
  }

  return ''
}
```

**Comment by silviuaavram** [comment]
Hi! I believe we have a PR that aims to fix the issue. Should be the last
one open, can you check please?

**Comment by diondiondion** [comment]
Hi @silviuaavram, thank you for addressing this so quickly!

I wasn't able to test the change before it was released, and it seems to work fine in all the demos now.

However in my own implementation where the results are loaded async (with a controlled `inputValue`), the default `getA11yStatusMessage` doesn't do any announcements. I plugged in my own function and noticed that the function is always called with `resultCount` and `previousResultCount` being identical:

![image](https://user-images.githubusercontent.com/5636050/84486426-b2555080-ac9d-11ea-81e0-39dfdbd8ff15.png)

Do you have any idea what might be causing this?

I tried to work around this by taking `previousResultCount` out of the equation. So I changed the conditional from 
https://github.com/downshift-js/downshift/blob/45985a893a6b12e12627c2c4ba87966e8826cd65/src/utils.js#L153

to 

```js
if (resultCount > 0) {
```

Now I get "staggered", out of sync announcements, i.e. if the resultset changes quickly from 1 to 4 to 6, it first reads "1 result is available, use up and down...", then "4 results are availeble...", and then "6 results...", instead of just the latest relevant update.

Unfortunately I wasn't able to recreate any of these issues in Codesandbox, but maybe you have an idea based on `previousResultCount` and `resultCount` being identical.

If I create my own declarative live region [as described above](https://github.com/downshift-js/downshift/issues/1076#issuecomment-640710481), everything works as expected and only the most recent update is announced.

Any help would be highly appreciated!

**Comment by silviuaavram** [comment]
@diondiondion can you provide a sandbox with this? It should work now.

And the check `resultCount !== previousResultCount` is mostly not relevant anymore, since most screen readers will ignore aria messages that are the same as the previous announcement. In other words, the resultCount really needs to change in order to be announced. And it should, if `items` is updated properly.

**Comment by diondiondion** [comment]
> @diondiondion can you provide a sandbox with this? It should work now.

Sorry, I desperately tried doing so this morning but couldn't reproduce it in Codesandbox using the basic demos as a starting point. :( I may give it another go next week.

> And the check resultCount !== previousResultCount is mostly not relevant anymore

It's still present in the default `getA11yStatusMessage` though, so if both come through identical for whatever reason like in my case, the message won't be updated.
