### ISSUE TITLE
Mobile touch events cause multiple onSelectedItemChange calls

### ISSUE THREAD

**Issue by Mighty683** [downshift-js/downshift#1534]
- `downshift` version: 7.6.0
- `node` version: 20

**What you did**:

On my project I have an issue that in some cases downshift calls onSelectedItemChange in a loop which crash application.
I made an reproduction which reproduce this problem with double call.

Seems to be the cause of issue: [1511](https://github.com/downshift-js/downshift/issues/1511)

**What happened**:

onSelectedItemChange function is called multiple times on mobile devices, depending on how complex component is, number of calls increase

**Reproduction repository**:

[Reproduction](https://codesandbox.io/s/elated-lichterman-4r2943?file=/src/App.tsx)

1. Open sandbox in a new window
2. Turn on mobile simulation with touch events enabled
3. Select some option and check console for counts of calls.

**Problem description**:

Issue seems to be connected to re-renders on onSelectedItemChange cause more calls it cause.

**Comment by TetriPetri** [comment]
I ran into this issue today but I came to the conclusion that it is a problem that is related the responsive tool and simulated touch events.

For example it does not work in chrome when you select device type: mobile
<img width="613" alt="image" src="https://github.com/downshift-js/downshift/assets/111516218/08e2ce5d-0455-4583-8463-f6220fd1de53">

I booted up my site with ngrok and ran on an iPhone 12 mini and ran into no issues with chrome and safari.

I have not tested it on a live site though.

Did you test on real devices?

**Comment by Mighty683** [comment]
Yes I am able to reproduce this issue on real devices, also on Firefox mobile emulator.

**Comment by Mighty683** [comment]
> I ran into this issue today but I came to the conclusion that it is a problem that is related the responsive tool and simulated touch events.
> 
> For example it does not work in chrome when you select device type: mobile
> <img width="613" alt="image" src="https://github.com/downshift-js/downshift/assets/111516218/08e2ce5d-0455-4583-8463-f6220fd1de53">
> 
> I booted up my site with ngrok and ran on an iPhone 12 mini and ran into no issues with chrome and safari.
> 
> I have not tested it on a live site though.
> 
> Did you test on real devices?
> 
> Edit: I just ran your codesandbox on my iPhone 12 mini, chrome without issues. Maybe android related?

Did you opened it in new window? I noticed that sandbox on codepen needs to be opened separately to be able to reproduce this issue.

**Comment by TetriPetri** [comment]
Yes, it runs on my iPhone without any issues. Here are the exact steps:

1. Open chrome on iPhone 12 mini.
2. Go to: https://4r2943.csb.app/
3. Toggle dropdown open
<img width="436" alt="image" src="https://github.com/downshift-js/downshift/assets/111516218/529a4ea2-9367-4a03-a091-8183112eb5d9">

4. Select option 2
<img width="444" alt="image" src="https://github.com/downshift-js/downshift/assets/111516218/4f0fccd2-b7ed-430c-8fb1-4ad48765cd8d">

5. Repeat 3 and 4 without problems.

6. Open safari on the iPhone
7. Repeat 2-5 without problems

**Comment by Mighty683** [comment]
I was testing on Android device

**Comment by TetriPetri** [comment]
> 

I can confirm, tested on Android device today and was able to reproduce!

**Comment by FdelMazo** [comment]
This is also affecting me on react 18 w/downshift 8.2.0

**Comment by silviuaavram** [comment]
If someone can investigate this issue it will be really helpful.

**Comment by silviuaavram** [comment]
I did some investigating. In React18, for touch events, there is one extra click event.

For instance, if you select an item by touch, the events are: click, mouse move, click. In 17, there is only mouse move then click.

Investigating further.

**Comment by silviuaavram** [comment]
Something must have changed with React `useReducer`. The dispatch causes the issue. To illustrate

```ts
      <button
        onClick={() => dispatch('click')}
        onMouseMove={() => dispatch('move')}
      >
        Touch me
      </button>
```

**Comment by silviuaavram** [comment]
Asking the React folks about it. https://github.com/facebook/react/issues/27666

**Comment by silviuaavram** [comment]
Still looking into it, as I went along a wrong trail previously.

**Comment by silviuaavram** [comment]
This issue seems to happen when we have both onClick and onMouseMove that trigger dispatch. Updated the Issue on React: https://github.com/facebook/react/issues/27666

I hope to find an elegant solution, as our state logic with useReducer is pretty complex and I would not want to refactor that.

**Comment by FdelMazo** [comment]
Thanks so much for taking a look at it @silviuaavram ! Your work is impressive

**Comment by silviuaavram** [comment]
Everyone, try `downshift@8.2.4-alpha.1`. If this solves the issue and does not break anything, we will release it as normal 8.2.4. Thank you!

https://www.npmjs.com/package/downshift/v/8.2.4-alpha.1

**Comment by silviuaavram** [comment]
It appears fixed with 8.2.4. I cannot repro it in that sandbox anymore.

**Comment by ramon-villain** [comment]
@silviuaavram I'm still facing this issue when running e2e with cypress, onClick is firing twice and as soon as I `omit` the `onMouseMove` property it works similarly to React 17.

I'll try to put together a repro branch over the next few days.

**Comment by silviuaavram** [comment]
@ramon-villain this is something that's related to React 18, I filed an issue there but no luck so far. I may need to dig into React myself.

For instance, this code will trigger the clicking action twice.

```js
import * as React from 'react'

function reducer(state, action) {
  switch (action.type) {
    case 'incremented_age': {
      console.log('here')
      return {
        name: state.name,
        age: state.age + 1,
      }
    }
    case 'changed_name': {
      console.log('here 2')
      return {
        name: action.nextName,
        age: state.age,
      }
    }
    case 'haha': {
      console.log('here 3')
      return {
        name: 'haha',
        age: state.age,
      }
    }
    default: {
      throw Error('Unknown action: ' + action.type)
    }
  }
}

const initialState = {name: 'Taylor', age: 42}

export default function App() {
  return (
    // <React.StrictMode>
    <Form />
    // </React.StrictMode>
  )
}

function Form() {
  const [state, dispatch] = React.useReducer(reducer, initialState)

  function handleButtonClick() {
    dispatch({type: 'incremented_age'})
  }

  function handleInputChange(e) {
    dispatch({
      type: 'changed_name',
      nextName: e.target.value,
    })
  }

  function handleMove(e) {
    e.preventDefault()
    dispatch({type: 'haha'})
  }

  return (
    <>
      <input value={state.name} onChange={handleInputChange} />
      <button onClick={handleButtonClick} onMouseMove={handleMove}>
        Increment agess
      </button>
      <p>
        Hello, {state.name}. You are {state.age}.
      </p>
    </>
  )
}
```
